/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Game {
  constructor(props: GameProps)
  join(props: JoinProps): void
  leave(id: number): void
  update(): void
  getPackagePerPlayer(id: number): string
}

export declare class GameProps {
  constructor(config: string, worlds: Array<string>)
}

export declare class JoinProps {
  name: string
  id: number
  constructor(name: string, id: number)
}
