/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ComputeEngine {
  constructor(props: EngineProps)
  join(playerProps: JoinProps): void
  leave(playerId: number): void
  chatMessage(content: string, id: number): void
  input(id: number, input: Input): void
  onPlayerDeath(callback: (arg: number) => null): void
  update(): object
}

export declare class EngineProps {
  constructor(config: string, worlds: Array<string>)
}

export declare class Input {
  left: boolean
  right: boolean
  up: boolean
  down: boolean
  shift: boolean
  mouseEnable: boolean
  mousePosX: number
  mousePosY: number
  firstAbility: boolean
  secondAbility: boolean
  constructor()
  setLeft(val: boolean): void
  setRight(val: boolean): void
  setUp(val: boolean): void
  setDown(val: boolean): void
  setShift(val: boolean): void
  setMouseEnable(val: boolean): void
  setMousePosX(val: number): void
  setMousePosY(val: number): void
  setFirstAbility(val: boolean): void
  setSecondAbility(val: boolean): void
}

export declare class JoinProps {
  name: string
  id: number
  constructor(name: string, id: number)
}

export declare class Vector {
  x: number
  y: number
}
