/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Game {
  constructor(props: GameProps)
  join(props: JoinProps): void
  leave(id: number): void
  input(id: number, input: InputProps): void
  update(): object
}

export declare class GameProps {
  constructor(config: string, worlds: Array<string>)
}

export declare class InputProps {
  left: boolean
  right: boolean
  up: boolean
  down: boolean
  shift: boolean
  mouseEnable: boolean
  mousePosX: number
  mousePosY: number
  firstAbility: boolean
  secondAbility: boolean
  constructor()
  setLeft(val: boolean): void
  setRight(val: boolean): void
  setUp(val: boolean): void
  setDown(val: boolean): void
  setShift(val: boolean): void
  setMouseEnable(val: boolean): void
  setMousePosX(val: number): void
  setMousePosY(val: number): void
  setFirstAbility(val: boolean): void
  setSecondAbility(val: boolean): void
}

export declare class JoinProps {
  name: string
  id: number
  constructor(name: string, id: number)
}

export declare class Vector {
  x: number
  y: number
  constructor(x?: number | undefined | null, y?: number | undefined | null)
}
